### ISSUE TITLE
Places name review

### ISSUE THREAD

**Issue by wannering** [BREDFactory/flex-server#52]
Review the nomenclature of squares, using the principle of urbanisation Site > Floor > Zone > Islet > Block: JV-4-R-Bois-4310B
o Site: JV (Joinville), LR (La Rapée)
o Floor : OK that's good
o Zone (Side):  Joinville (Green zone, blue zone, red zone), LR (Whole Floor)
o Islet: Joinville (RER, Bois, Milieu), LR (Seine, Cour)
o Number: Number under the flap under the docking stations

We are waiting for details of the places names

**Comment by canatac** [comment]
I changed the site abbr. in Azure CosmosDB

**Comment by canatac** [comment]
We need the last desktop numbers in JV-4-R-Bois-4310B. For the moment, numbers increment by one in each Islet.
